# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-19 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=200, null=True)),
                ('suburb', models.CharField(blank=True, max_length=200, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=200, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.CharField(blank=True, max_length=1024, null=True)),
                ('longitude', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Adresses',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                ('latitude', models.CharField(blank=True, max_length=1024, null=True)),
                ('longitude', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'ordering': ['-name'],
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2)),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='PointOfSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                ('fantasy_name', models.CharField(max_length=1024)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.Address')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.Category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StateProvince',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=3)),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.Country')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1024)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='visit.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('user_id', models.CharField(max_length=200)),
                ('arrival', models.DateTimeField()),
                ('departure', models.DateTimeField()),
                ('total_time_in_min', models.IntegerField()),
                ('precision', models.IntegerField()),
                ('pdv', models.BooleanField(default=False)),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='visit.PointOfSale')),
            ],
            options={
                'ordering': ['arrival'],
            },
        ),
        migrations.AddField(
            model_name='pointofsale',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visit.SubCategory'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.StateProvince'),
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.City'),
        ),
    ]
